### ISSUE TITLE
Modifiche richieste dai vertici

### ISSUE THREAD

**Issue by AchilleDiNevesa** [rssntn67/gestioneAttrezzatura#2]
1) In gestione operabili > attrezzatura > aggiungi attrezzatura nella sezione modello ( il menù a tendina per intenderci )  manca tipo  e marca ( fondamentale per identificare cosa inserire ). 
2)In modello attrezzatura  la sezione NOME è superflua  e tenderemo a non inserirla ma è tuttavia necessaria per salvare il modello e non può essere ne vuota ne due volte la stessa voce . L'unica cosa sempre necessaria è il Tipo , consiglio quella come identificativo sempre necessario.
3)in gestione consumabili dopo avvenute le varie operazioni di carico e scarico , in caso di scarico sarebbe molto comodo integrare un sistema di DDT in modo da generarlo automaticamente .
4) L'attrezzatura Cassoni che precedentemente si era pensato di inserire come una normale attrezzatura ha bisogno di voci particolari come il volume espresso in m^3 ed un inserimento di foto quindi credo vada creata un altra sezione a parte, quindi sostituire nome con matricola
5) il punto uno e due si ripete anche nel personale e nei consumabili quindi va corretto.

In definitiva hanno visto il programma molto macchinoso ed è stato chiesto di semplificarlo , ma facendo le modifiche sopra indicate i modelli diventerebbero più chiari e molti meno e quindi diventa molto facile vederli .
Mi dica se vede le prove effettuate i modelli le attrezzature ed i fornitori inseriti.
Se come penso sostituire il Nome col Tipo in quanto deve essere ogni volta non ripetuto mi è stato chiesto di unire gestione modello e gestione operabili in modo da inserire in un unica sezione il tutto e non creare aggiunte ridondanti.
Richiedo anche informazioni sul procedimento per modificare le cose riportate nel punto 1 in quanto le ho modificate la sezione che per me è corrispondente a ciò ma non ho visto differenze.

**Comment by AchilleDiNevesa** [comment]
edit , mi ha cambiato i numeri , i punti da modificare sono 5 in totale

**Comment by rssntn67** [comment]
Caro Achille,
 Questo tipo di modifiche ti consiglio di farle tu.
 Io ti ho fatto vedere come è fatto il programma.
 Oggi mi ha chiamato Antonio Giardino.
 Lunedì pomeriggio sono da te in Gardenia, ma sono modifiche che farai tu.
 Come ho ampiamente scritto, gestioneAttrezzatura non è un programma di gestione magazzino.
 Bisogna ragionare in termini di carico e scarico li e quindi integrare.
 Grande errore fare un programma che deve fare tutto.
 In genere non funziona.
 Ora il punto 1 lo puoi fare tu da solo e la parte ddt non se ne parla. Non da valore ed è una cosa che fa gaveira.
 Manteniamo sempre chiaro il nostro obiettivo mio caro.

 Saluti

Antonio
